### ISSUE TITLE
你好，按照您的设置之后无法使用，请问怎么解决？

### ISSUE THREAD

**Issue by ChuGary** [barrer/translate-online#2]
![image](https://user-images.githubusercontent.com/60617720/76522250-44806980-64a1-11ea-9a79-b7c5367f8b8d.png)
![image](https://user-images.githubusercontent.com/60617720/76522256-477b5a00-64a1-11ea-9830-f6e6662f6d3d.png)

**Comment by barrer** [comment]
这个项目已经不再维护，请使用：https://github.com/barrer/tampermonkey-script
